# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('date_started', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
